//! Domain types for the P21 session store.
//!
//! These mirror the four tables in the design doc (sessions / messages /
//! workflow_runs / agent_calls). Numeric timestamps are Unix seconds (i64) and
//! JSON columns are `serde_json::Value`.

use serde::{Deserialize, Serialize};

/// Lifecycle status of a session.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum SessionStatus {
    /// Normal, active session.
    Active,
    /// Soft-archived (hidden from default listing, data retained).
    Archived,
    /// Soft-deleted (`delete_session`); data retained, excluded from queries.
    Deleted,
}

/// A session — the top-level aggregate root. Every message / workflow run /
/// agent call hangs under a `session_id`.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Session {
    /// UUID v4, generated by the app (not auto-increment).
    pub id: String,
    /// Associated agent id (from AGENT.yaml). No agent-less bare sessions.
    pub agent_id: String,
    /// Reserved for multi-user extension.
    pub user_id: String,
    /// User-set or auto-generated title.
    pub title: Option<String>,
    pub created_at: i64,
    pub updated_at: i64,
    /// JSON metadata (tags / extra).
    pub metadata: serde_json::Value,
    pub status: SessionStatus,
}

/// Role of a message in a conversation. `Tool` captures agent↔skill I/O.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum MessageRole {
    User,
    Assistant,
    System,
    Tool,
}

/// A single message within a session.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Message {
    /// Rowid assigned by SQLite on insert (0 when constructing for append).
    pub id: i64,
    pub session_id: String,
    pub role: MessageRole,
    pub content: String,
    /// JSON `[{name, arguments, result?}]`; only populated when `role == Tool`.
    pub tool_calls: Option<serde_json::Value>,
    /// Links a tool message back to its calling message.
    pub tool_call_id: Option<String>,
    pub created_at: i64,
    /// Rough token estimate, for context-window management.
    pub token_count: i64,
}

/// Lifecycle status of a workflow run record.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum WorkflowRunStatus {
    Pending,
    Running,
    Completed,
    Failed,
    Terminated,
}

/// A workflow execution record — the *user-level* view of one workflow call.
/// Step-level detail lives in P17 `RunStore` under `temp/workflows`; this table
/// stores only entry input and final output.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct WorkflowRunRecord {
    /// UUID v4.
    pub id: String,
    pub session_id: String,
    pub workflow_name: String,
    pub workflow_version: Option<String>,
    /// JSON workflow input.
    pub input: Option<serde_json::Value>,
    /// JSON final output.
    pub output: Option<serde_json::Value>,
    pub status: WorkflowRunStatus,
    pub started_at: i64,
    pub finished_at: Option<i64>,
    /// Error detail, only when `status == Failed`.
    pub error: Option<String>,
    /// Whether this run hit the P20 intermediate-result cache or executed for real.
    pub cache_hit: bool,
}

/// An agent call audit record — the full user→agent→skill chain.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct AgentCallRecord {
    /// UUID v4.
    pub id: String,
    pub session_id: String,
    pub agent_id: String,
    pub user_input: String,
    pub assistant_response: Option<String>,
    /// JSON `["skill_a", "skill_b"]`.
    pub skills_used: Vec<String>,
    /// Semantic-router final skill (from P12).
    pub matched_skill: Option<String>,
    /// Router confidence.
    pub confidence: Option<f64>,
    /// Total call latency in ms.
    pub latency_ms: Option<i64>,
    pub created_at: i64,
}
